### ISSUE TITLE
usage instructions?

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#1]
trying to import into a folk for osmdroid. 

getting
````Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.

```
```

**Comment by spyhunter99** [comment]
some notes as follows.

add `apply from......` to your android projects

create gradle.properties using the included file as an example

**Comment by chrisdoyle** [comment]
Good call.  On it, look for it by end of weekend.  :)

**Comment by chrisdoyle** [comment]
Done!  Thanks for the nudge.
