### ISSUE TITLE
feature request, store generated pom.xml in build folder

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#17]
it would be useful to store the generated pom's in the build folder for people construction distribution packages with pom's + output artifacts

**Comment by chrisdoyle** [comment]
@spyhunter99, I believe this already happens when you execute any of the `publishToMavenLocal`, `install`, `uploadArchives` or `publish` tasks.  The generated `pom.xml` resides beneath the `build/publications/[name]/` directory.  Is that what you were looking for?

**Comment by spyhunter99** [comment]
ahh i see what I was missing. The publish of the parent pom doesn't store to disk, it's possible that it doesn't publish. It also looks like child pom's do not reference the parent. Ugh. I guess in this case, any build step related stuff doesn't matter, so long as the dependencies are all there.
