### ISSUE TITLE
feature request, provide credentials via command line?

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#19]
is it possible to supply signing certificates and nexus u/p via the command line?

**Comment by chrisdoyle** [comment]
Like the idea!  Not sure though, might be able to use standard Gradle command-line trickery for this?  Will do some experimentation and let you know.

**Comment by chrisdoyle** [comment]
Gradle actually supports this using the `-P` or `--project-prop` parameter from the command-line to support overriding property values:

`./gradlew clean install -Ppom.organization.name="Initech"`
**OR**
`./gradlew clean install --project-prop pom.organization.name="Initech"`

I am not going to admit how long it took me to figure this out, as I was in a Gradle black hole.  #gradleface

![Gradle Face](https://pbs.twimg.com/media/CpZdqPFUkAA-QI5.jpg)
