### ISSUE TITLE
Publishing to maven central errors

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#27]
Support a "name" pom element for all child modules
Need to mediate gradle's wild card syntax for versioning to maven's syntax

**Comment by spyhunter99** [comment]
Descriptions are not added to the pom either. Willing to bet gradle changed some api that breaks stuff.  System.out.println for the bits that alter the name and description return "[]"

**Comment by spyhunter99** [comment]
https://discuss.gradle.org/t/how-to-publish-artifacts-signatures-asc-files-using-maven-publish-plugin/7422

which links to this
https://github.com/gradle/gradle/blob/master/design-docs/publication-model.md

cliff notes, pgp signing to .asc files is NOT supported with gradle. All other solutions, like bintray, upload unsigned artifacts, then signs it server side. We may be able to use pgp command line to sign the artifacts, but i'm clueless on how to force it to upload.

**Comment by spyhunter99** [comment]
so i found a way to call pgp and generate asc files, however it's not firing in the right order. It appears to be firing before any compiling where as we want it to fire after the after thing but before publish/release

```

def signFile(file){
    System.out.println("attempting to sign " + file)
    exec {

        executable '/usr/local/bin/gpg'

        args "-a", "--output", file+".asc","--detach-sig",file
        standardOutput = new ByteArrayOutputStream()
        ext.output = {
            return standardOutput.toString()
        }

    }
}
```

**Comment by chrisdoyle** [comment]
But Gradle's task ordering is supposed to be pure, unfiltered awesome, I thought?  Just look at their documentation:

https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:ordering_tasks

OH WAIT A MINUTE:

> Task ordering is an incubating feature. Please be aware that this feature may change in later Gradle versions.

So very, very surprising that they would leave what I would consider a core feature in incubation.   Maybe this is a really new feature that they wanted to preview to us common folk, you know, to work out the kinks.  Some quick digging in their vastly superior documentation uncovered that Task Ordering was introduced with version 1.6 of Gradle:

https://docs.gradle.org/1.6/userguide/more_about_tasks.html#sec:ordering_tasks

The current version at the time of this comment is 3.0.  1.6 was released on May 7, 2013:

https://discuss.gradle.org/t/gradle-1-6-released/7664/1

Based on this, the Gradle folks apparently define "incubation" as at least more than 1200+ days, and spanning multiple major version releases.  I vote that we adopt this kind of flexibility into our development lifecycle, please.

**Comment by chrisdoyle** [comment]
I haven't tried myself, but have you tried adding the following?

`publish.mustRunAfter signFile`

**Comment by spyhunter99** [comment]
remaining work, 
- pom signatures need to be uploaded
- war file support?
- filenames are a bit jacked up and non-standard. i'm not sure if there's an alternate solution aside from writing our own publish mechanism from scratch.

**Comment by spyhunter99** [comment]
surprise surprise, war projects are handled completely different that Jar/Android projects in the publish side
