### ISSUE TITLE
minSdkVersion from module build.gradle gets overwritten

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#6]
I'm trying to switch osmdroid over to this library and in the gradle.properties file, minSdkVersion is 8, however several modules require a higher minSdkVersion and have declared that in the build.gradle file. The module looks like ( just the relevant parts)

```
android {
    compileSdkVersion 'Google Inc.:Google APIs:23'
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "org.osmdroid.google.sample"
        minSdkVersion 9
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
}
```

gradle.properties looks like this

```
android.buildToolsVersion=23.0.2
android.compileSdkVersion=23
android.minSdkVersion=8
android.targetSdkVersion=23

```

build output

```
:GoogleWrapperSample:processDebugManifest
/Users/xxxx/osmdroid/GoogleWrapperSample/src/main/AndroidManifest.xml:4:5-73 Error:
    uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library [com.google.android.gms:play-services:8.4.0] /Users/xxxx/osmdroid/GoogleWrapperSample/build/intermediates/exploded-aar/com.google.android.gms/play-services/8.4.0/AndroidManifest.xml
    Suggestion: use tools:overrideLibrary="com.google.android.gms.all" to force usage

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:GoogleWrapperSample:processDebugManifest FAILED
```

I'm willing to bet the root cause is the lack of an extra if (!defined) type of check for minSdkVersion.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/

branch: bug/#321Fury

**Comment by chrisdoyle** [comment]
Interesting catch!  Will take a look at and get back to you.

**Comment by chrisdoyle** [comment]
@spyhunter99,

I checked out your branch from the osmdroid project, and was able to get beyond this condition by moving the "apply from: .../android-support.gradle" statement above the android closure, which seems to allow for the overridden values.  So you should be able to move forward by adjusting each of the affected build.gradle files.  In the meantime, I will continue looking for a code solution in gradle-fury itself so it will work either way.

**Comment by spyhunter99** [comment]
ahh good call

**Comment by spyhunter99** [comment]
confirmed that this fix works. apply gradlefury before the android section of your build.gradle file
