### ISSUE TITLE
local publishing fails if the gradle plugin is > 1.3.1

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#8]
definitely does not publish with 1.5.0 or 2.0.0, they must have changed something

**Comment by spyhunter99** [comment]
related reference material http://tools.android.com/tech-docs/new-build-system/version-compatibility

**Comment by chrisdoyle** [comment]
Another great catch.  And sadly unfortunate, as it completely invalidates current usage of gradle-fury.  This already smells like a black hole of Gradle, I'll start digging...

**Comment by spyhunter99** [comment]
the only reference i see in the 1.5.0 release notes is this

> Deprecated the dex getter from the ApplicationVariant class. You can't access the Dex task through the variant API anymore because it’s now accomplished through a transform. There's currently no replacement for controlling the dex process.

**Comment by chrisdoyle** [comment]
Awaiting PR #10 approval.
