### ISSUE TITLE
site plugin

### ISSUE THREAD

**Issue by spyhunter99** [chrisdoyle/gradle-fury#96]
for discussion. not sure what else the maven site plugin does
- [x] copy test reports
- [x] copy lint reports
- [x] aggregate anything else?
- [x] copy javadocs (copy to right location)
- [x] copy some kind of themed artifacts
- [x] copy user provided docs into build dir
- [x] reports support
  - [x] junit tests
  - [x] android connected check
  - [x] android lint
  - [x] findbugs
  - [x] jacoco
  - [x] checkstyle
  - [x] jdepends
  - [x] java ncss report 
- [x] generate "canned" site artifacts similiar to maven
  - [x] repositories
  - [x] artifact list?
  - [x] issue tracking
  - [x] licenses
  - [x] team 
  - [x] source repo
  - [x] reports
  - [x] java docs
- [x] inject site index and any globable variables into user defined site content
- [x] convert alter user defined site content into html
  - [x] asciidoc
  - [x] markdown
- [x] create a site index
- [x] dependency report for all modules/variants
- [x] render reports and javadocs in an iframe to give everything more of a themed look
- [x] overridable the output dir

**Comment by spyhunter99** [comment]
https://github.com/gradle/gradle/blob/master/design-docs/reporting.md

**Comment by spyhunter99** [comment]
http://gradle.1045684.n5.nabble.com/Maven-site-and-report-plugins-td1432286.html

**Comment by spyhunter99** [comment]
http://gradle.1045684.n5.nabble.com/Site-generation-including-content-td1432914.html

**Comment by spyhunter99** [comment]
@MasonLiuChn thanks for the quality plugin, just dropping you a line that i'm borrowing your work on this one. I also made a bunch of changes to support non-android projects too

**Comment by spyhunter99** [comment]
@azagniotov thanks for the jdepend setup you made on stubby4j. just dropping you a line that I'm borrowing the setup and have adapted it for both android and java projects.

**Comment by azagniotov** [comment]
No worries. I am glad it helped you in some way!

**Comment by spyhunter99** [comment]
Need to be able to override the output dir
